# Generated by Django 6.0 on 2025-12-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author_contacts',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контакты автора'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на курс (YT/Сайт)'),
        ),
    ]
