# Generated by Django 6.0 on 2025-12-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендовать на главной'),
        ),
    ]
