# Generated by Django 6.0 on 2025-12-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-is_pinned', 'order', '-enrolled_at']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
